name: gan_ucsf_08
results_path: ./predictions_adv
batch_size: 16
num_workers: 4

datasets:
  name: ucsf
  dataroot: ./data/UCSF-PDGM
  sampling_mask: radial  # or linear
  seed: 31415
  type: FLAIR  # or other MRI type
  pathology: []  # list of pathologies to include
  lower_slice: 60
  upper_slice: 130
  split: test
  num_rays: 60

models:
  network: GAN
  model_path: ./code/pix2pix/checkpoints/200_net_G.pth
  
task_models: 
  name: ucsf
  models: 
    - type: classifier
      name: TGradeBCEClassifier
      path: ./models/tgrade/checkpoints/tgrade.pth
    - type: classifier
      name: TTypeBCEClassifier
      path: ./models/ttype/checkpoints/ttype.pth
    - type: segmentation
      name: UNet
      path: ./models/segmentation_skews/segmentatio/segmentation.pth