output_dir: './output'
output_name: 'unet-ucsf'
save_interval: 1
dataset: 'ucsf'

num_epochs: 20
learning_rate: 0.0001
batch_size: 8
early_stopping_patience: 5

dataroot: '../../data/UCSF-PDGM'
type: 'T2'
lower_slice: 60
upper_slice: 130
age_bins: [0, 58, 100]

network_type: 'UNet'
sampling_mask: 'radial'
seed: 31415
